subjects = ["C", "C++", "Java", "C#", "Python", "R", "Ruby", "Dart"]
print(subjects)
print(subjects[0])
print(len(subjects))
print(subjects[2:])
print(subjects[::2])
print(subjects[2:6])
print(subjects[2:6:2])
print(subjects[::-1])
print(subjects + ["Go"])
print("Swift" in subjects)
print("Swift" not in subjects)
subjects.append("Swift")
print(subjects)
subjects.pop()
print(subjects)
subjects.insert(2, "php")
print(subjects)
subjects.remove("php")
print(subjects)