numbers = [45, 3, 22, 10, 78, 50, 22, 3, 5, 73, 3]
print(numbers)
print(numbers.index(22))
numbers.remove(45)
print(numbers)
print(numbers.count(22))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers2 = numbers.copy()
numbers2.reverse()
print(numbers2)
numbers2.clear()
print(numbers2)